
class ExceptionHandler:
    def __init__(self):
        pass
